### ISSUE TITLE
[activation] explanation of the value of the small addition in elu activation

### ISSUE THREAD

**Issue by cyrilou242** [cpmpercussion/keras-mdn-layer#7]
Hello, I am trying to understand your implementation.

In the activation function:
`def elu_plus_one_plus_epsilon(x):`
`    """ELU activation with a very small addition to help prevent NaN in loss."""`
`    return (K.elu(x) + 1 + 1e-8)`

Do you have any reason for using `1e-8` ? Default tensor flow fuzz factor K.epsilon() value is `1e-7`, and going with a smaller value could (in theory) make some computations unstable. (don't have any example sorry).

Also, maybe using something like `K.clip(K.elu(x) + 1 , K.epsilon())` or with your value `K.clip(K.elu(x) + 1 , 1e-8)` would make more sense in the activation function ?

**Comment by cpmpercussion** [comment]
Hi, no particular reason, just trying to avoid the standard deviations reaching zero.

I think `K.clip(K.elu(x) + 1 , K.epsilon())` seems most elegant, so that would probably be better! I'll try it out this week.

**Comment by cyrilou242** [comment]
Thanks, I was more wondering about the specific `1e-8` value than the coding with `K.clip`.
I'll give a try with different epsilon when I have the time. 
I think this issue can be closed.

**Comment by cpmpercussion** [comment]
No particular reason to choose 1e-8, your argument makes sense and K.epsilon() seems like a better choice.

Wouldn't using `K.clip` potentially remove some potential gradient if `K.elu(x) + 1 < K.epsilon()`? I guess that was the idea for just using addition.
