### ISSUE TITLE
2D MDN example not working

### ISSUE THREAD

**Issue by HassamSheikh** [cpmpercussion/keras-mdn-layer#9]
I was running you 2D example on local machine and I came across this error

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    history = model.fit(x=x_input, y=y_input, batch_size=128, epochs=300, validation_split=0.15, callbacks=[keras.callbacks.TerminateOnNaN()])
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 960, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1572, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected mdn_1 to have shape (None, 50) but got array with shape (5000, 2)

**Comment by cpmpercussion** [comment]
Hi @HassamSheikh, 

Him, I can't seem to reproduce that issue. Can you confirm what versions of python / TensorFlow / tensorflow probability you are using?

The 2D example seems to train with Python 3.6.8 (Anaconda), and the versions listed in the requirements file:

```
Keras==2.2.4
numpy==1.16.1
tensorflow==1.12.0
tensorflow-probability==0.5.0
```

I'm just trying now with tensorflow 1.13.1.

**Comment by HassamSheikh** [comment]
I am not sure, where are things going wrong but I am just running a small part of the code. The versions I am using are the one you wrote in the update.
```
import keras
import mdn
import numpy as np
import random
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

NSAMPLE = 5000

z_data = np.float32(np.random.uniform(-10.5, 10.5, NSAMPLE))
r_data = np.random.normal(size=NSAMPLE)
s_data = np.random.normal(size=NSAMPLE)
x_data = np.sin(0.75 * z_data) * 7.0 + z_data * 0.5 + r_data * 1.0
y_data = np.cos(0.80 * z_data) * 6.5 + z_data * 0.5 + s_data * 1.0

x_input = z_data.reshape((NSAMPLE, 1))
y_input = np.array([x_data,y_data])
y_input = y_input.T #reshape to (NSAMPLE,2)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(x_data, y_data, z_data, alpha=0.3, c='r') #c=perf_down_sampled.moving
plt.show()

N_HIDDEN = 15
N_MIXES = 10
OUTPUT_DIMS = 2

model = keras.Sequential()
model.add(keras.layers.Dense(N_HIDDEN, batch_input_shape=(None, 1), activation='relu'))
model.add(keras.layers.Dense(N_HIDDEN, activation='relu'))
model.add(mdn.MDN(OUTPUT_DIMS, N_MIXES))
model.compile(loss=mdn.get_mixture_loss_func(OUTPUT_DIMS,N_MIXES), optimizer=keras.optimizers.Adam())
model.summary()
history = model.fit(x=x_input, y=y_input, batch_size=128, epochs=300, validation_split=0.15, callbacks=[keras.callbacks.TerminateOnNaN()])

```

**Comment by HassamSheikh** [comment]
ok, so I tried in python 3.6.  It works perfectly fine.
